### ISSUE TITLE
Make a Purchase of Stationery and Office Supplies January

### ISSUE THREAD

**Issue by xaviperalta** [Casumo/BarcelonaOffice#33]
We need to buy new stuff for the office.

**Comment by xaviperalta** [comment]
@Casumo/barcelona-team Today I'll make a big purchase of Stationery and Office Supplies for the Barcelona Office. If you are missing something please feel free to post your needs in here this morning. 

- [ ] HDMI input to DVI (20).

- [ ] HDMI to HDMI cables (10).

- [ ] UK-EU plug (20).

- [ ] USB C Hub (10).

- [ ] Lightning - USB Cable (10).

- [ ] 4 UK Power Strips.

**Comment by westymalik** [comment]
Hi Xavi,
I'll need MAC USB-C to Ethernet cable and spain-to-uk power adapter please.
Thanks & Regards,
Westy

**Comment by xaviperalta** [comment]
I already added them Westy!

**Comment by westymalik** [comment]
Great Thanks!

**Comment by AndyJWCasumo** [comment]
I know it's old skool but could we get some pads and pens?! :D

**Comment by xaviperalta** [comment]
We have some of them in the office but I will order some more. You are not the only old school ;)

**Comment by xaviperalta** [comment]
After some problems with the Amazon Account we finally purchased all the stuff. 

- [ ] Add all the stuff to the Inventory.
