### ISSUE TITLE
Organize Casumo Breakfast Meeting 16th January

### ISSUE THREAD

**Issue by xaviperalta** [Casumo/BarcelonaOffice#9]
Next 16th of January we have a new Casumo Breakfast Meeting. We want to encourage all our Sumo's in the Barcelona Office to join this event in the office and enjoy it together.

**Comment by xaviperalta** [comment]
- [ ] Communication Plan.

- [ ] Arrange breakfast for our Sumo's.

- [ ] Check every technical detail so we are sure everything is working propperly.

**Comment by sarakvarfordt** [comment]
I'll order some fresh juices and smoothies from Theresas, they will have to be delivered Monday afternoon since they do not make early morning deliveries.

**Comment by xaviperalta** [comment]
Sara took care of it.
